--
-- table
--
create table {SCHEMA}fetch_tiktok_campaigns (
    advertiser_id character varying(64) NOT NULL,
    account_timezone character varying(64),
    company_display_name character varying(1024) NOT NULL,
    account_currency character varying(8) NOT NULL,
    campaign_active_register double precision,
    campaign_skip double precision,
    campaign_active_register_rate double precision,
    campaign_active_rate double precision,
    campaign_active_pay_amount double precision,
    campaign_active_pay_avg_amount double precision,
    campaign_dy_comment double precision,
    campaign_active_pay_cost double precision,
    campaign_conversion_rate double precision,
    campaign_active_pay_show double precision,
    campaign_ecpm double precision,
    campaign_campaign_name character varying(8192) NOT NULL,
    campaign_active_register_click_cost double precision,
    campaign_stat_datetime date NOT NULL,
    campaign_active_register_show_cost double precision,
    campaign_active_register_click double precision,
    campaign_conversion_cost double precision,
    campaign_active_click_cost double precision,
    campaign_stat_cost double precision,
    campaign_active_pay_click_cost double precision,
    campaign_active_register_cost double precision,
    campaign_active_pay_click double precision,
    campaign_dy_like double precision,
    campaign_active_pay_rate double precision,
    campaign_click_cost double precision,
    campaign_active_show double precision,
    campaign_active_click double precision,
    campaign_active double precision,
    campaign_convert_cnt double precision,
    campaign_show_cnt double precision,
    campaign_campaign_id character varying(64),
    campaign_dy_share double precision,
    campaign_activate_cost double precision,
    campaign_ctr double precision,
    campaign_active_pay double precision,
    campaign_active_cost double precision,
    campaign_active_register_show double precision,
    campaign_active_pay_show_cost double precision,
    campaign_activate_rate double precision,
    campaign_time_attr_convert_cnt double precision,
    campaign_click_cnt double precision,
    campaign_dy_home_visited double precision,
    campaign_active_show_cost double precision,
    campaign_budget_mode character varying(128),
    campaign_budget double precision,
    campaign_objective_type character varying(128),
    campaign_create_time datetime,
    campaign_modify_time datetime,
    campaign_status character varying(64),
    campaign_opt_status character varying(64),
    campaign_objective character varying(128),
    extracted_os_types character varying(8192),
    extracted_product character varying(1024),
    extracted_product_id character varying(256),
    extracted_product_name character varying(1024),
    extracted_product_os character varying(128),
    platform character varying(128),
    product character varying(1024),
    product_id character varying(256),
    product_name character varying(1024),
    product_platform character varying(128),
    product_os character varying(128),
    converted_currency character varying(8),
    latest_campaign_name character varying(8192),
    currency_conversion_rate double precision,
    crystallized bool NOT NULL default true,
    fetch_date datetime,
    PRIMARY KEY (campaign_campaign_id, campaign_stat_datetime)
)
distkey (campaign_stat_datetime)
sortkey (campaign_stat_datetime, campaign_campaign_id);
