--
-- table
--
create table {SCHEMA}fetch_google_ads_ad_assets (
  customer_id character varying(765),
  customer_descriptive_name character varying(765),
  customer_currency_code character varying(9),
  campaign_id character varying(765),
  campaign_name character varying(765),
  campaign_status character varying(189),
  campaign_app_campaign_setting_app_id character varying(189),
  campaign_app_campaign_setting_app_store character varying(189),
  ad_group_id character varying(189),
  ad_group_name character varying(6138),
  ad_group_status character varying(189),
  ad_group_type character varying(189),
  ad_group_base_ad_group character varying(189),
  ad_group_ad_ad_id character varying(189),
  ad_group_ad_ad_name character varying(6138),
  ad_group_ad_status character varying(189),
  ad_group_ad_ad_type character varying(189),
  asset_resource_name character varying(189),
  asset_id character varying(189),
  asset_name character varying(6138),
  asset_type character varying(189),
  ad_group_ad_asset_view_resource_name character varying(765),
  ad_group_ad_asset_view_field_type character varying(189),
  ad_group_ad_asset_view_performance_label character varying(189),
  ad_group_ad_asset_view_policy_summary character varying(32768),
  metrics_cost_micros bigint,
  metrics_impressions bigint,
  metrics_clicks bigint,
  metrics_conversions double precision,
  metrics_conversions_value double precision,
  metrics_all_conversions double precision,
  segments_date date not null,
  cost double precision,
  extracted_product character varying(765),
  product character varying(765),
  product_id character varying(189),
  product_name character varying(765),
  product_platform character varying(765),
  product_os character varying(189),
  latest_customer_descriptive_name character varying(765),
  latest_campaign_name character varying(6138),
  latest_ad_group_name character varying(6138),
  latest_ad_group_ad_name character varying(6138),
  latest_asset_name character varying(6138),
  converted_currency character varying(9),
  currency_conversion_rate double precision,
  company_display_name character varying(765) not null,
  ad_display_name character varying(6138),
  ad_asset_url character varying(6138),
  latest_ad_display_name character varying(6138),
  latest_ad_asset_url character varying(6138),
  crystallized bool NOT NULL default true,
  fetch_date datetime,
  PRIMARY KEY (ad_group_ad_ad_id, segments_date)
)
distkey (segments_date)
sortkey (segments_date, ad_group_ad_ad_id);
