--
-- table
--
CREATE TABLE {SCHEMA}performance_cube_unfiltered (
    source character varying(765) not null,
    row_type character varying(765) not null,
    effective_date date not null,
    entity_granularity character varying(765) not null,
    cohort_granularity character varying(765) not null,
    time_granularity character varying(765) not null,
    product_id character varying(765),
    product_name character varying(765),
    channel character varying(765),
    mmp character varying(765),
    campaign_id character varying(765),
    adset_id character varying(765),
    ad_id character varying(765),
    platform character varying(64),
    event_name character varying(765),
    daily_cohort date,
    weekly_cohort date,
    event_day bigint,
    event_week bigint,
    event_month bigint,
    cohort_events bigint,
    cohort_revenue double precision,
    time_series_events bigint,
    time_series_revenue double precision,
    spend double precision,
    impressions bigint,
    clicks bigint,
    relevance_score double precision,
    reach bigint,
    frequency double precision,
    campaign_name character varying(6138),
    adset_name character varying(6138),
    ad_name character varying(6138),
    campaign_tag character varying(765),
    campaign_subtag character varying(765),
    adset_tag character varying(6138),
    adset_subtag character varying(765),
    ad_tag character varying(6138),
    ad_subtag character varying(765),
    ad_type character varying(189),
    campaign_status character varying(189),
    adset_status character varying(189),
    ad_status character varying(189),
    first_impression_date date,
    campaign_objective character varying(765),
    creative_id character varying(765),
    creative_name character varying(6138),
    creative_title character varying(32768),
    creative_body character varying(32768),
    creative_image_url character varying(6138),
    creative_thumbnail_url character varying(6138),
    channel_crystallized boolean,
    mmp_crystallized boolean,
    crystallized boolean,
    dynamic_segments character varying(32768),
    dynamic_metrics character varying(32768)
)
distkey (effective_date)
sortkey (source, effective_date);
