--
-- table
--
create table {SCHEMA}fetch_tiktok_adgroups (
  advertiser_id character varying(64) NOT NULL,
  account_timezone character varying(64),
  company_display_name character varying(1024) NOT NULL,
  account_currency character varying(8) NOT NULL,
  adgroup_adgroup_id character varying(64) NOT NULL,
  adgroup_adgroup_name character varying(8192) NOT NULL,
  adgroup_campaign_id	character varying(64) NOT NULL,
  adgroup_campaign_name	character varying(8192) NOT NULL,
  adgroup_placement_type character varying(128),
  adgroup_placement	character varying(1024),
  adgroup_enable_inventory_filter	bool,
  adgroup_landing_page_url character varying(2048),
  adgroup_display_name character varying(8192),
  adgroup_app_id character varying(64),
  adgroup_app_download_url character varying(2048),
  adgroup_open_url character varying(2048),
  adgroup_app_name character varying(1024),
  adgroup_app_type character varying(128),
  adgroup_package	character varying(128),
  adgroup_category int,
  adgroup_keywords character varying(8192),
  adgroup_avatar_icon character varying(8192),
  adgroup_is_comment_disable bool,
  adgroup_android_osv	character varying(64),
  adgroup_ios_osv	character varying(64),
  adgroup_audience character varying(256),
  adgroup_excluded_audience	character varying(256),
  adgroup_gender character varying(64),
  adgroup_location character varying(256),
  adgroup_age	character varying(1024),
  adgroup_languages	character varying(1024),
  adgroup_connection_type	character varying(1024),
  adgroup_operation_system character varying(128),
  adgroup_device_price character varying(256),
  adgroup_interest_category	character varying(1024),
  adgroup_budget double precision,
  adgroup_budget_mode	character varying(64),
  adgroup_pacing character varying(64),
  adgroup_frequency character varying(1024),
  adgroup_frequency_schedule character varying(1024),
  adgroup_schedule_type	character varying(64),
  adgroup_schedule_start_time	datetime,
  adgroup_schedule_end_time	datetime,
  adgroup_dayparting character varying(8192),
  adgroup_billing_event	character varying(64),
  adgroup_bid	double precision,
  adgroup_conversion_id	character varying(64),
  adgroup_skip_learning_phase	bool,
  adgroup_conversion_bid double precision,
  adgroup_impression_tracking_url	character varying(2048),
  adgroup_click_tracking_url character varying(2048),
  adgroup_video_view_tracking_url	character varying(2048),
  adgroup_create_time	datetime,
  adgroup_modify_time	datetime,
  adgroup_creative_material_mode character varying(64),
  adgroup_optimize_goal	character varying(64),
  adgroup_external_action	character varying(128),
  adgroup_deep_external_action character varying(128),
  adgroup_deep_bid_type	character varying(64),
  adgroup_status character varying(64),
  adgroup_active_register double precision,
  adgroup_skip double precision,
  adgroup_active_register_rate double precision,
  adgroup_active_rate double precision,
  adgroup_active_pay_amount double precision,
  adgroup_active_pay_avg_amount double precision,
  adgroup_dy_comment double precision,
  adgroup_active_pay_cost double precision,
  adgroup_conversion_rate double precision,
  adgroup_active_pay_show double precision,
  adgroup_ecpm double precision,
  adgroup_active_register_click_cost double precision,
  adgroup_stat_datetime date NOT NULL,
  adgroup_active_register_show_cost double precision,
  adgroup_dy_like double precision,
  adgroup_conversion_cost double precision,
  adgroup_active_click_cost double precision,
  adgroup_stat_cost double precision,
  adgroup_active_pay_click_cost double precision,
  adgroup_active_register_cost double precision,
  adgroup_active_pay_click double precision,
  adgroup_active_register_click double precision,
  adgroup_active_pay_rate double precision,
  adgroup_click_cost double precision,
  adgroup_active_show double precision,
  adgroup_active_click double precision,
  adgroup_active double precision,
  adgroup_convert_cnt double precision,
  adgroup_show_cnt double precision,
  adgroup_dy_share double precision,
  adgroup_activate_cost double precision,
  adgroup_ctr double precision,
  adgroup_active_pay double precision,
  adgroup_active_cost double precision,
  adgroup_active_register_show double precision,
  adgroup_active_pay_show_cost double precision,
  adgroup_activate_rate double precision,
  adgroup_time_attr_convert_cnt double precision,
  adgroup_click_cnt double precision,
  adgroup_dy_home_visited double precision,
  adgroup_active_show_cost double precision,
  adgroup_pixel_id character varying(128),
  adgroup_profile_image character varying(2048),
  adgroup_deep_cpabid double precision,
  adgroup_opt_status character varying(64),
  adgroup_bid_type character varying(128),
  adgroup_statistic_type character varying(128),
  extracted_os_types character varying(8192),
  extracted_product character varying(1024),
  extracted_product_id character varying(256),
  extracted_product_name character varying(1024),
  extracted_product_os character varying(128),
  platform character varying(128),
  product character varying(1024),
  product_id character varying(256),
  product_name character varying(1024),
  product_platform character varying(128),
  product_os character varying(128),
  converted_currency character varying(8),
  latest_adgroup_name character varying(8192),
  currency_conversion_rate double precision,
  crystallized bool NOT NULL default true,
  fetch_date datetime,
  PRIMARY KEY (adgroup_adgroup_id, adgroup_stat_datetime)
)
distkey (adgroup_stat_datetime)
sortkey (adgroup_stat_datetime, adgroup_adgroup_id);
