--
-- table
--
create table {SCHEMA}fetch_apple_search_ads_campaigns (
    adamid character varying(765) not null,
    appname character varying(765),
    avgcpa double precision,
    avgcpt double precision,
    campaignid character varying(765) not null,
    campaignname character varying(6138),
    campaignstatus character varying(765),
    conversionrate double precision,
    conversions double precision,
    conversionslatoff double precision,
    conversionslaton double precision,
    conversionsnewdownloads double precision,
    conversionsredownloads double precision,
    dailybudget double precision,
    date date not null,
    deleted bool,
    displaystatus character varying(765),
    impressions double precision,
    localspend double precision,
    modificationtime timestamp without time zone,
    servingstatereasons character varying(6138),
    servingstatus character varying(765),
    storefront character varying(765),
    taps double precision,
    totalbudget double precision,
    ttr double precision,
    supplysources character varying(8192),
    adchanneltype character varying(256),
    company_display_name character varying(765),
    org_id character varying(765) not null,
    org_name character varying(765),
    app_display_name character varying(765),
    platform character varying(765),
    product character varying(765),
    product_id character varying(189),
    product_name character varying(765),
    product_platform character varying(765),
    product_os character varying(189),
    latest_campaign_name character varying(6138),
    original_currency character varying(9),
    converted_currency character varying(9),
    currency_conversion_rate double precision,
    crystallized bool NOT NULL default true,
    fetch_date datetime,
    PRIMARY KEY (campaignid, "date")
)
distkey ("date")
sortkey ("date", campaignid);
