--
-- table
--
create table {SCHEMA}fetch_google_ads_ads (
  customer_id character varying(765),
  customer_descriptive_name character varying(765),
  customer_currency_code character varying(9),
  campaign_id character varying(765),
  campaign_name character varying(765),
  campaign_status character varying(189),
  campaign_app_campaign_setting_app_id character varying(189),
  campaign_app_campaign_setting_app_store character varying(189),
  ad_group_id character varying(189),
  ad_group_name character varying(6138),
  ad_group_status character varying(189),
  ad_group_type character varying(189),
  ad_group_base_ad_group character varying(189),
  ad_group_ad_ad_id character varying(189),
  ad_group_ad_ad_name character varying(6138),
  ad_group_ad_status character varying(189),
  ad_group_ad_ad_type character varying(189),
  ad_group_ad_ad_app_ad_html5_media_bundles character varying(32768),
  ad_group_ad_ad_app_ad_images character varying(32768),
  ad_group_ad_ad_app_ad_headlines character varying(32768),
  ad_group_ad_ad_app_ad_descriptions character varying(32768),
  ad_group_ad_ad_app_ad_mandatory_ad_text character varying(6138),
  ad_group_ad_ad_app_ad_youtube_videos character varying(32768),
  ad_group_ad_ad_app_engagement_ad_images character varying(32768),
  ad_group_ad_ad_app_engagement_ad_videos character varying(32768),
  ad_group_ad_ad_call_only_ad_description1 character varying(6138),
  ad_group_ad_ad_call_only_ad_description2 character varying(6138),
  ad_group_ad_ad_call_only_ad_headline1 character varying(765),
  ad_group_ad_ad_call_only_ad_headline2 character varying(765),
  ad_group_ad_ad_display_upload_ad_media_bundle character varying(32768),
  ad_group_ad_ad_display_url character varying(6138),
  ad_group_ad_ad_expanded_dynamic_search_ad_description character varying(6138),
  ad_group_ad_ad_expanded_dynamic_search_ad_description2 character varying(6138),
  ad_group_ad_ad_expanded_text_ad_description character varying(6138),
  ad_group_ad_ad_expanded_text_ad_description2 character varying(6138),
  ad_group_ad_ad_expanded_text_ad_headline_part1 character varying(765),
  ad_group_ad_ad_expanded_text_ad_headline_part2 character varying(765),
  ad_group_ad_ad_expanded_text_ad_headline_part3 character varying(765),
  ad_group_ad_ad_gmail_ad_marketing_image_description character varying(6138),
  ad_group_ad_ad_gmail_ad_marketing_image_display_call_to_action_text character varying(765),
  ad_group_ad_ad_gmail_ad_marketing_image_headline character varying(765),
  ad_group_ad_ad_gmail_ad_teaser_description character varying(6138),
  ad_group_ad_ad_gmail_ad_teaser_headline character varying(765),
  ad_group_ad_ad_image_ad_image_url character varying(6138),
  ad_group_ad_ad_image_ad_name character varying(765),
  ad_group_ad_ad_image_ad_preview_image_url character varying(6138),
  ad_group_ad_ad_legacy_responsive_display_ad_description character varying(6138),
  ad_group_ad_ad_legacy_responsive_display_ad_promo_text character varying(6138),
  ad_group_ad_ad_legacy_responsive_display_ad_short_headline character varying(765),
  ad_group_ad_ad_responsive_display_ad_descriptions character varying(32768),
  ad_group_ad_ad_responsive_display_ad_headlines character varying(32768),
  ad_group_ad_ad_responsive_display_ad_logo_images character varying(32768),
  ad_group_ad_ad_responsive_display_ad_long_headline character varying(765),
  ad_group_ad_ad_responsive_display_ad_marketing_images character varying(32768),
  ad_group_ad_ad_responsive_display_ad_promo_text character varying(6138),
  ad_group_ad_ad_responsive_display_ad_square_logo_images character varying(32768),
  ad_group_ad_ad_responsive_display_ad_square_marketing_images character varying(32768),
  ad_group_ad_ad_responsive_display_ad_youtube_videos character varying(32768),
  ad_group_ad_ad_responsive_search_ad_descriptions character varying(32768),
  ad_group_ad_ad_responsive_search_ad_headlines character varying(32768),
  ad_group_ad_ad_shopping_comparison_listing_ad_headline character varying(765),
  ad_group_ad_ad_text_ad_description1 character varying(6138),
  ad_group_ad_ad_text_ad_description2 character varying(6138),
  ad_group_ad_ad_text_ad_headline character varying(765),
  ad_group_ad_ad_video_ad_in_stream_action_headline character varying(765),
  ad_group_ad_ad_video_ad_out_stream_description character varying(6138),
  ad_group_ad_ad_video_ad_out_stream_headline character varying(765),
  metrics_cost_micros bigint,
  metrics_impressions bigint,
  metrics_clicks bigint,
  metrics_conversions double precision,
  metrics_conversions_value double precision,
  metrics_all_conversions double precision,
  segments_date date not null,
  cost double precision,
  extracted_product character varying(765),
  product character varying(765),
  product_id character varying(189),
  product_name character varying(765),
  product_platform character varying(765),
  product_os character varying(189),
  latest_customer_descriptive_name character varying(765),
  latest_campaign_name character varying(6138),
  latest_ad_group_name character varying(6138),
  latest_ad_group_ad_name character varying(6138),
  converted_currency character varying(9),
  currency_conversion_rate double precision,
  company_display_name character varying(765) not null,
  ad_display_name character varying(6138),
  ad_asset_url character varying(6138),
  latest_ad_display_name character varying(6138),
  latest_ad_asset_url character varying(6138),
  crystallized bool NOT NULL default true,
  fetch_date datetime,
  PRIMARY KEY (ad_group_ad_ad_id, segments_date)
)
distkey (segments_date)
sortkey (segments_date, ad_group_ad_ad_id);
