--
-- table
--
create table {SCHEMA}fetch_tiktok_ads (
  advertiser_id character varying(64) NOT NULL,
  account_timezone character varying(64),
  company_display_name character varying(1024) NOT NULL,
  account_currency character varying(8) NOT NULL,
  ad_active_register double precision,
  ad_skip double precision,
  ad_active_register_rate double precision,
  ad_active_rate double precision,
  ad_active_pay_amount double precision,
  ad_active_pay_avg_amount double precision,
  ad_dy_comment double precision,
  ad_active_pay_cost double precision,
  ad_active double precision,
  ad_conversion_rate double precision,
  ad_active_pay_show double precision,
  ad_ecpm double precision,
  ad_campaign_name character varying(8192),
  ad_active_register_click_cost double precision,
  ad_stat_datetime date NOT NULL,
  ad_adgroup_id character varying(64) NOT NULL,
  ad_active_register_show_cost double precision,
  ad_dy_like double precision,
  ad_conversion_cost double precision,
  ad_active_click_cost double precision,
  ad_adgroup_name character varying(8192),
  ad_stat_cost double precision,
  ad_active_pay_click_cost double precision,
  ad_active_register_cost double precision,
  ad_active_pay_click double precision,
  ad_ad_id character varying(64) NOT NULL,
  ad_active_register_click double precision,
  ad_active_pay_rate double precision,
  ad_ad_text character varying(8192),
  ad_click_cost double precision,
  ad_active_show double precision,
  ad_active_click double precision,
  ad_ad_name character varying(8192),
  ad_convert_cnt double precision,
  ad_show_cnt double precision,
  ad_campaign_id character varying(64) NOT NULL,
  ad_dy_share double precision,
  ad_activate_cost double precision,
  ad_ctr double precision,
  ad_active_pay double precision,
  ad_active_cost double precision,
  ad_active_register_show double precision,
  ad_active_pay_show_cost double precision,
  ad_activate_rate double precision,
  ad_time_attr_convert_cnt double precision,
  ad_click_cnt double precision,
  ad_dy_home_visited double precision,
  ad_active_show_cost double precision,
  ad_status character varying(64),
  ad_opt_status character varying(64),
  ad_call_to_action character varying(128),
  ad_video_id character varying(128),
  ad_image_ids character varying(2048),
  ad_create_time datetime,
  ad_modify_time datetime,
  ad_is_aco bool,
  ad_image_mode character varying(64),
  ad_profile_image character varying(2048),
  ad_click_tracking_url character varying(2048),
  ad_display_name character varying(1024),
  ad_impression_tracking_url character varying(2048),
  ad_video_view_tracking_url character varying(2048),
  ad_landing_page_url character varying(2048),
  ad_open_url character varying(2048),
  ad_app_name character varying(1024),
  extracted_os_types character varying(8192),
  extracted_product character varying(1024),
  extracted_product_id character varying(256),
  extracted_product_name character varying(1024),
  extracted_product_os character varying(128),
  platform character varying(128),
  product character varying(1024),
  product_id character varying(256),
  product_name character varying(1024),
  product_platform character varying(128),
  product_os character varying(128),
  converted_currency character varying(8),
  latest_ad_name character varying(8192),
  currency_conversion_rate double precision,
  crystallized bool NOT NULL default true,
  fetch_date datetime,
  PRIMARY KEY (ad_ad_id, ad_stat_datetime)
)
distkey (ad_stat_datetime)
sortkey (ad_stat_datetime, ad_ad_id);
