--
-- table
--
create table {SCHEMA}fetch_google_ads_ad_conversion_actions (
  customer_id character varying(765),
  customer_descriptive_name character varying(765),
  customer_currency_code character varying(9),
  campaign_id character varying(765),
  campaign_name character varying(765),
  campaign_status character varying(189),
  campaign_app_campaign_setting_app_id character varying(189),
  campaign_app_campaign_setting_app_store character varying(189),
  ad_group_id character varying(189),
  ad_group_name character varying(6138),
  ad_group_status character varying(189),
  ad_group_type character varying(189),
  ad_group_base_ad_group character varying(189),
  ad_group_ad_ad_id character varying(189),
  ad_group_ad_ad_name character varying(6138),
  ad_group_ad_status character varying(189),
  ad_group_ad_ad_type character varying(189),
  metrics_conversions double precision,
  metrics_conversions_value double precision,
  metrics_all_conversions double precision,
  segments_date date not null,
  segments_conversion_action character varying(765),
  segments_conversion_action_category character varying(189),
  segments_conversion_action_name character varying(6138),
  conversion_action_id character varying(765),
  conversion_action_name character varying(6138),
  conversion_action_type character varying(189),
  conversion_action_category character varying(189),
  conversion_action_app_id character varying(189),
  conversion_action_value_settings_default_value double precision,
  conversion_action_value_settings_default_currency_code character varying(189),
  metrics_conversion_last_conversion_date date,
  extracted_product character varying(765),
  product character varying(765),
  product_id character varying(189),
  product_name character varying(765),
  product_platform character varying(765),
  product_os character varying(189),
  latest_customer_descriptive_name character varying(765),
  latest_campaign_name character varying(6138),
  latest_ad_group_name character varying(6138),
  latest_ad_group_ad_name character varying(6138),
  converted_currency character varying(9),
  currency_conversion_rate double precision,
  company_display_name character varying(765) not null,
  crystallized bool NOT NULL default true,
  fetch_date datetime,
  PRIMARY KEY (ad_group_ad_ad_id, segments_conversion_action, segments_date)
)
distkey (segments_date)
sortkey (segments_date, ad_group_ad_ad_id, segments_conversion_action);
